#pragma once

#include <stdint.h>
#include "usb_config.h"
#include "usb_util.h"

/*
 * This firmware only runs one USB ethernet host class at a time, so the
 * transfer and control buffers can share one DMA-safe internal pool.
 */

#ifdef CONFIG_CHERRYUSB_HOST_CDC_ECM
#define USBH_ETH_CDC_ECM_RX_SIZE     USB_ALIGN_UP(1514U, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_CDC_ECM_TX_SIZE     USB_ALIGN_UP(1514U, CONFIG_USB_ALIGN_SIZE)
#else
#define USBH_ETH_CDC_ECM_RX_SIZE     0U
#define USBH_ETH_CDC_ECM_TX_SIZE     0U
#endif

#ifdef CONFIG_CHERRYUSB_HOST_CDC_RNDIS
#define USBH_ETH_RNDIS_RX_SIZE       USB_ALIGN_UP(CONFIG_USBHOST_RNDIS_ETH_MAX_RX_SIZE, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_RNDIS_TX_SIZE       USB_ALIGN_UP(CONFIG_USBHOST_RNDIS_ETH_MAX_TX_SIZE, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_RNDIS_CTRL_SIZE     USB_ALIGN_UP(512U, CONFIG_USB_ALIGN_SIZE)
#else
#define USBH_ETH_RNDIS_RX_SIZE       0U
#define USBH_ETH_RNDIS_TX_SIZE       0U
#define USBH_ETH_RNDIS_CTRL_SIZE     0U
#endif

#ifdef CONFIG_CHERRYUSB_HOST_CDC_NCM
#define USBH_ETH_CDC_NCM_RX_SIZE     USB_ALIGN_UP(CONFIG_USBHOST_CDC_NCM_ETH_MAX_RX_SIZE, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_CDC_NCM_TX_SIZE     USB_ALIGN_UP(CONFIG_USBHOST_CDC_NCM_ETH_MAX_TX_SIZE, CONFIG_USB_ALIGN_SIZE)
#else
#define USBH_ETH_CDC_NCM_RX_SIZE     0U
#define USBH_ETH_CDC_NCM_TX_SIZE     0U
#endif

#ifdef CONFIG_CHERRYUSB_HOST_ASIX
#define USBH_ETH_ASIX_RX_SIZE        USB_ALIGN_UP(CONFIG_USBHOST_ASIX_ETH_MAX_RX_SIZE, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_ASIX_TX_SIZE        USB_ALIGN_UP(CONFIG_USBHOST_ASIX_ETH_MAX_TX_SIZE, CONFIG_USB_ALIGN_SIZE)
#else
#define USBH_ETH_ASIX_RX_SIZE        0U
#define USBH_ETH_ASIX_TX_SIZE        0U
#endif

#ifdef CONFIG_CHERRYUSB_HOST_RTL8152
#define USBH_ETH_RTL8152_RX_SIZE     USB_ALIGN_UP(CONFIG_USBHOST_RTL8152_ETH_MAX_RX_SIZE, CONFIG_USB_ALIGN_SIZE)
#define USBH_ETH_RTL8152_TX_SIZE     USB_ALIGN_UP(CONFIG_USBHOST_RTL8152_ETH_MAX_TX_SIZE, CONFIG_USB_ALIGN_SIZE)
#else
#define USBH_ETH_RTL8152_RX_SIZE     0U
#define USBH_ETH_RTL8152_TX_SIZE     0U
#endif

enum {
	USBH_ETH_SHARED_CTRL_SIZE =
		USBH_ETH_RNDIS_CTRL_SIZE > USB_ALIGN_UP(32U, CONFIG_USB_ALIGN_SIZE) ? USBH_ETH_RNDIS_CTRL_SIZE : USB_ALIGN_UP(32U, CONFIG_USB_ALIGN_SIZE),
	USBH_ETH_SHARED_INT_SIZE = USB_ALIGN_UP(16U, CONFIG_USB_ALIGN_SIZE),
	USBH_ETH_SHARED_RX_SIZE_0 = USBH_ETH_CDC_ECM_RX_SIZE > USBH_ETH_RNDIS_RX_SIZE ? USBH_ETH_CDC_ECM_RX_SIZE : USBH_ETH_RNDIS_RX_SIZE,
	USBH_ETH_SHARED_RX_SIZE_1 = USBH_ETH_CDC_NCM_RX_SIZE > USBH_ETH_ASIX_RX_SIZE ? USBH_ETH_CDC_NCM_RX_SIZE : USBH_ETH_ASIX_RX_SIZE,
	USBH_ETH_SHARED_RX_SIZE_2 = USBH_ETH_SHARED_RX_SIZE_0 > USBH_ETH_SHARED_RX_SIZE_1 ? USBH_ETH_SHARED_RX_SIZE_0 : USBH_ETH_SHARED_RX_SIZE_1,
	USBH_ETH_SHARED_RX_SIZE = USBH_ETH_SHARED_RX_SIZE_2 > USBH_ETH_RTL8152_RX_SIZE ? USBH_ETH_SHARED_RX_SIZE_2 : USBH_ETH_RTL8152_RX_SIZE,
	USBH_ETH_SHARED_TX_SIZE_0 = USBH_ETH_CDC_ECM_TX_SIZE > USBH_ETH_RNDIS_TX_SIZE ? USBH_ETH_CDC_ECM_TX_SIZE : USBH_ETH_RNDIS_TX_SIZE,
	USBH_ETH_SHARED_TX_SIZE_1 = USBH_ETH_CDC_NCM_TX_SIZE > USBH_ETH_ASIX_TX_SIZE ? USBH_ETH_CDC_NCM_TX_SIZE : USBH_ETH_ASIX_TX_SIZE,
	USBH_ETH_SHARED_TX_SIZE_2 = USBH_ETH_SHARED_TX_SIZE_0 > USBH_ETH_SHARED_TX_SIZE_1 ? USBH_ETH_SHARED_TX_SIZE_0 : USBH_ETH_SHARED_TX_SIZE_1,
	USBH_ETH_SHARED_TX_SIZE = USBH_ETH_SHARED_TX_SIZE_2 > USBH_ETH_RTL8152_TX_SIZE ? USBH_ETH_SHARED_TX_SIZE_2 : USBH_ETH_RTL8152_TX_SIZE
};

/* WiCAN: heap-backed (internal DMA), refcounted - allocated on the
 * first eth-class connect, freed on the last disconnect. Every eth
 * class driver MUST call usbh_eth_shared_buf_alloc() at the top of
 * its connect() and usbh_eth_shared_buf_free() in disconnect(). */
extern uint8_t *g_usbh_eth_shared_rx_buffer;
extern uint8_t *g_usbh_eth_shared_tx_buffer;
extern uint8_t *g_usbh_eth_shared_int_buffer;
extern uint8_t *g_usbh_eth_shared_ctrl_buffer;

int usbh_eth_shared_buf_alloc(void);
void usbh_eth_shared_buf_free(void);
void usbh_eth_shared_buf_force_free(void);